### ISSUE TITLE
[Epic] Creating the foundation!

### ISSUE THREAD

**Issue by RickyBaca28** [RickyBaca28/Fig-It#1]
# Description 
First step in this project is to install all the tools framework we plan to use!

### Dependencies
- [x] Node.js (https://nodejs.org/en/)  #2
- [x] mongoDB (https://www.npmjs.com/package/mongodb) (https://phoenixnap.com/kb/docker-mongodb) #2
- [x] React (https://www.javatpoint.com/react-installation) (https://reactjs.org/) #2 
- [x] Docker (https://docs.docker.com/docker-for-mac/install/) #2
- [x]  Express (https://www.npmjs.com/package/express) #2
- [ ]  Redis 
- [ ] Lerna (https://medium.com/@rachitabansal/introduction-to-lerna-3fb7382a4d4e)

### Miscellaneous 
- [ ]  some sort of unit testing (jest) #7 
- [ ] CD/CI pipeline
- [x]  Good code architecture #2

### Toolkits to have
- mongoCompass or robo3t (https://robomongo.org/download)
- insomnia or postman (https://insomnia.rest)
