### ISSUE TITLE
TEST: Create unit test for items endpoint

### ISSUE THREAD

**Issue by RickyBaca28** [RickyBaca28/Fig-It#27]
# Description
Now that we have jest unit testing lets create unit for our new endpoints!

## TODO
- [ ] integration test
- [x] controller layer test
- [x] service layer test
- [ ] db layer test
- [ ] model layer test
