### ISSUE TITLE
[EPIC] Trade History

### ISSUE THREAD

**Issue by RickyBaca28** [RickyBaca28/Fig-It#34]
# Description 

## implementation 1
- [ ]  Confirmation of traded item to be inserted into trade history (POST)
- [ ]  List of traded items (w/ search key being item) (GET)
- [ ] List of traded items (w/ search key being user) (GET)
- [ ] Global traded items list (GET)

## implementation 2
- [ ] Global traded items list (GET)
