### ISSUE TITLE
[EPIC] Create User endpoint

### ISSUE THREAD

**Issue by RickyBaca28** [RickyBaca28/Fig-It#9]
# Description 
Just like how we have our `item` endpoint (`http://localhost:7777/api/v1/items`) 

## Iterations

- [x] Create `user` model #20 
- [x] Create `user` DB #21 
- [x]  Create `user` service #22
- [x]  Create `user` controller #23
- [x] Create `user` routes #24

**Comment by mRenga** [comment]
Epic complete
